# Generated by Django 3.2 on 2023-05-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_auto_20230505_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
