# Generated by Django 3.2 on 2023-05-10 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_alter_proveedor_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{7,}$', message='El número de teléfono debe tener al menos 7 dígitos')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono2',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{7,}$', message='El número de teléfono debe tener al menos 7 dígitos')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=40, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.IntegerField(null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{7,}$', message='El número de teléfono debe tener al menos 7 dígitos')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono2',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{7,}$', message='El número de teléfono debe tener al menos 7 dígitos')]),
        ),
    ]
