# Generated by Django 3.2 on 2023-05-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_auto_20230510_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [('ver_proveedor', 'Puede ver proveedores'), ('agregar_proveedor', 'Puede agregar proveedores'), ('editar_proveedor', 'Puede editar proveedores'), ('eliminar_proveedor', 'Puede eliminar proveedores')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
