# Generated by Django 3.2 on 2023-05-11 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventario', '0021_auto_20230511_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='permiso_crear_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crear_proveedor', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='permiso_editar_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editar_proveedor', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='permiso_eliminar_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminar_proveedor', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='permiso_ver_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ver_proveedor', to='auth.permission'),
        ),
    ]
